#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess
import glob

def main():
    print("=== RAM-VI SLAM Code Protection & Release Compiler ===")
    
    # 1. Ensure Cython is installed
    try:
        import Cython
    except ImportError:
        print("Cython is not installed. Installing it now...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "cython"])
        
    dist_dir = 'dist'
    release_name = 'RAM_VI_SLAM'
    target_dir = os.path.join(dist_dir, release_name)
    
    # Clean previous builds
    shutil.rmtree(dist_dir, ignore_errors=True)
    os.makedirs(target_dir, exist_ok=True)
    
    # 2. Copy all files into target release directory
    print("Copying package assets...")
    shutil.copy('1.png', os.path.join(target_dir, '1.png'))
    shutil.copy('2.png', os.path.join(target_dir, '2.png'))
    shutil.copy('launcher.py', os.path.join(target_dir, 'launcher.py'))
    shutil.copy('setup.py', os.path.join(target_dir, 'setup.py'))
    shutil.copy('package.xml', os.path.join(target_dir, 'package.xml'))
    shutil.copy('requirements.txt', os.path.join(target_dir, 'requirements.txt'))
    shutil.copy('install.sh', os.path.join(target_dir, 'install.sh'))
    shutil.copy('run.sh', os.path.join(target_dir, 'run.sh'))
    shutil.copy('LICENSE', os.path.join(target_dir, 'LICENSE'))
    
    # Copy resource index folder (needed for colcon to register python packages)
    shutil.copytree('resource', os.path.join(target_dir, 'resource'), dirs_exist_ok=True)
    
    # Copy empty output dir template
    os.makedirs(os.path.join(target_dir, 'output'), exist_ok=True)
    
    # Copy ram_vi_slam package dir to target
    target_pkg_dir = os.path.join(target_dir, 'ram_vi_slam')
    shutil.copytree('ram_vi_slam', target_pkg_dir, dirs_exist_ok=True)
    
    # 3. Restructure entrypoint scripts inside dist package to support Cython
    print("Restructuring entrypoint files...")
    # Rename entrypoints to *_core.py
    os.rename(os.path.join(target_pkg_dir, 'offline_runner.py'), os.path.join(target_pkg_dir, 'offline_runner_core.py'))
    os.rename(os.path.join(target_pkg_dir, 'slam_node.py'), os.path.join(target_pkg_dir, 'slam_node_core.py'))
    
    # 4. Generate setup_compile.py inside target directory
    setup_compile_content = """from setuptools import setup
from Cython.Build import cythonize
import glob

py_files = [f for f in glob.glob("ram_vi_slam/*.py") if not f.endswith("__init__.py")]

setup(
    ext_modules=cythonize(py_files, compiler_directives={'language_level': "3"}),
)
"""
    setup_compile_path = os.path.join(target_dir, 'setup_compile.py')
    with open(setup_compile_path, 'w') as f:
        f.write(setup_compile_content)
        
    # 5. Compile python files to binary .so modules
    print("Compiling Python modules to native libraries using Cython...")
    try:
        subprocess.check_call([sys.executable, 'setup_compile.py', 'build_ext', '--inplace'], cwd=target_dir)
        print("Compilation successful.")
    except Exception as e:
        print(f"Error compiling extension modules: {e}")
        sys.exit(1)
        
    # 6. Delete source files and compiler files
    print("Cleaning up source code and compiler files...")
    # Remove all .py files in target package except __init__.py
    for py_file in glob.glob(os.path.join(target_pkg_dir, '*.py')):
        if not py_file.endswith('__init__.py'):
            os.remove(py_file)
            
    # Remove temporary .c files generated by Cython
    for c_file in glob.glob(os.path.join(target_pkg_dir, '*.c')):
        os.remove(c_file)
        
    # Remove compilation files
    os.remove(setup_compile_path)
    shutil.rmtree(os.path.join(target_dir, 'build'), ignore_errors=True)
    
    # 7. Write tiny clean wrapper Python files for offline_runner.py and slam_node.py (entrypoints)
    wrapper_runner = """# RAM-VI SLAM Offline Runner Wrapper
from .offline_runner_core import main
if __name__ == '__main__':
    main()
"""
    wrapper_node = """# RAM-VI SLAM Online ROS 2 Node Wrapper
from .slam_node_core import main
if __name__ == '__main__':
    main()
"""
    with open(os.path.join(target_pkg_dir, 'offline_runner.py'), 'w') as f:
        f.write(wrapper_runner)
    with open(os.path.join(target_pkg_dir, 'slam_node.py'), 'w') as f:
        f.write(wrapper_node)
        
    # Make scripts executable in target
    os.chmod(os.path.join(target_dir, 'install.sh'), 0o755)
    os.chmod(os.path.join(target_dir, 'run.sh'), 0o755)
    os.chmod(os.path.join(target_dir, 'launcher.py'), 0o755)
        
    # 8. Package to zip
    print("Creating ZIP release archive...")
    zip_path = shutil.make_archive('RAM_VI_SLAM_release_v1', 'zip', dist_dir, release_name)
    
    # Clean temporary dist folder
    shutil.rmtree(dist_dir, ignore_errors=True)
    
    print(f"\nSUCCESS: Obfuscated binary release package created at: {zip_path}")
    print("This ZIP contains only the compiled machine-code shared libraries (.so) for the SLAM modules.")
    print("Users can run the simulation launcher directly using './run.sh', but cannot read or edit your source code!")

if __name__ == '__main__':
    main()
